name: Update Metrics

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Metrics
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Amsterdam
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "chore: update `${filename}`"
          user: dusthijsvdh

          template: classic
          base: header, activity, community, repositories
          plugin_lines: yes

  language:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Languages
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Amsterdam
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "chore: update `${filename}`"
          user: dusthijsvdh

          filename: metrics.plugin.languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          repositories_skipped: dusthijsvdh/BGEMBJATWDHATBTGIA

  topics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Topics
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Amsterdam
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "chore: update `${filename}`"
          user: dusthijsvdh

          filename: metrics.plugin.topics.svg
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 10
          plugin_topics_mode: icons
  
  habits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Habits
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Amsterdam
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "chore: update `${filename}`"
          user: dusthijsvdh

          filename: metrics.plugin.habits.charts.svg
          base: ""
          plugin_habits: yes
          plugin_habits_from: 500
          plugin_habits_facts: yes
          plugin_habits_charts: yes

  achievments:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Achievments
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Amsterdam
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "chore: update `${filename}`"
          user: dusthijsvdh

          filename: metrics.plugin.achievements.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
  
  stackoverflow:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Stack Overflow
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Amsterdam
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "chore: update `${filename}`"
          user: dusthijsvdh

          filename: metrics.plugin.stackoverflow.svg
          base: ""
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 9117310
  
  wakatime:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Wakatime
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Amsterdam
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "chore: update `${filename}`"
          user: dusthijsvdh

          filename: metrics.plugin.wakatime.svg
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_repositories_visibility: public
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
  
  steam:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Steam
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Amsterdam
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "chore: update `${filename}`"
          user: dusthijsvdh
          
          filename: metrics.plugin.steam.svg
          base: ""
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: "76561198109279674"
          plugin_steam_games_limit: 1
          plugin_steam_achievements_limit: 1
