name: Update Metrics

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Metrics
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Amsterdam
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: 'chore: update `${filename}`'
          user: dustessavdh

          template: classic
          base: header, activity, repositories, metadata
          base_indepth: yes
          plugin_lines: yes
          plugin_lines_delay: 30
          plugin_traffic: yes

  language:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Languages
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Amsterdam
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: 'chore: update `${filename}`'
          user: dustessavdh

          filename: metrics.plugin.languages.svg
          base: ''
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          repositories_skipped: dustessavdh/BGEMBJATWDHATBTGIA

  habits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Habits
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Amsterdam
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: 'chore: update `${filename}`'
          user: dustessavdh

          filename: metrics.plugin.habits.charts.svg
          base: ''
          plugin_habits: yes
          plugin_habits_from: 500
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: yes

  achievments:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Achievments
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Amsterdam
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: 'chore: update `${filename}`'
          user: dustessavdh

          filename: metrics.plugin.achievements.svg
          base: ''
          plugin_achievements: yes
          plugin_achievements_display: compact

  stackoverflow:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Stack Overflow
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Amsterdam
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: 'chore: update `${filename}`'
          user: dustessavdh

          filename: metrics.plugin.stackoverflow.svg
          base: ''
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 9117310

  wakatime:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Wakatime
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Amsterdam
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: 'chore: update `${filename}`'
          user: dustessavdh

          filename: metrics.plugin.wakatime.svg
          base: ''
          plugin_wakatime: yes
          plugin_wakatime_repositories_visibility: public
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os

  steam:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Steam
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Amsterdam
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: 'chore: update `${filename}`'
          user: dustessavdh

          filename: metrics.plugin.steam.svg
          base: ''
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: '76561198109279674'
          plugin_steam_games_limit: 1
          plugin_steam_achievements_limit: 1

  xkcd:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: XKCD image of the day
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Amsterdam
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: 'chore: update `${filename}`'
          user: dustessavdh

          filename: metrics.plugin.xkcd.svg
          base: ''
          plugin_screenshot: yes
          plugin_screenshot_title: XKCD of the day
          plugin_screenshot_url: https://xkcd.com
          plugin_screenshot_selector: '#comic img'

  workchronicles:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Work Chronicles image of the day
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Amsterdam
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: 'chore: update `${filename}`'
          user: dustessavdh

          filename: metrics.plugin.workchronicles.svg
          base: ''
          plugin_screenshot: yes
          plugin_screenshot_title: Work Chronicles of the day
          plugin_screenshot_url: https://workchronicles.substack.com/p/comic-cool-thing-to-say
          plugin_screenshot_wait: 10000

  music:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Recently listened
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Amsterdam
          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: 'chore: update `${filename}`'
          user: dustessavdh

          filename: metrics.plugin.music.svg
          base: ''
          plugin_music: yes
          plugin_music_provider: lastfm
          plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
          plugin_music_user: JustAap
          plugin_music_mode: top
          plugin_music_played_at: yes
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_limit: 5
